In [1]:
import numpy as np

In [2]:
two_by_three = np.array([1,2,3,4,5,6]).reshape(2,3) # two arrays each of three elements

print("2x3\n",two_by_three)

three_by_two = np.array([1,2,3,4,5,6]).reshape(3,2) # three arrays each of two elements

print("\n3x2\n",three_by_two)


2x3
 [[1 2 3]
 [4 5 6]]

3x2
 [[1 2]
 [3 4]
 [5 6]]


#### Weights representation in NN

![image info](2x3network.png) ![image info](3x2Weights.png) 

Consider two layers l-1 and l , where l-1 has 2 neurons while l has 3 neurons. So there would be total 2\*3 interconnections (weights) between these two layers. Each neuron in layer l is connected to two (all) neurons in layer l-1 , also there would be 2 activations (from l-1 layer neurons) being consumed by layer l neurons. And 3 activations would be output from layer l. 

z = wa + b

if w and a are represensted in matrix form, we can calculate z easily, which would also be in the matrix form.

The weights can be represented in a 3x2 matrix : (3 rows and two columns), where  
each row j represents connections into $j^{th}$ neuron of layer l from 2 neurons of layer l-1.  
each column i represents connections starting from $i^{th}$ neuron of layer l-1.


In general, if there are m neurons in layer l-1 and n neurons in layer l, there would be m\*n weights. m input activations for layer l and n output activations from layer l. The weight matrix should be then n x m : n number of arrays, each of size m. The size m (number of columns) should match with the input number of activations as they would have one-to-one correspondance in the product. The size n (number of rows) should match with the output number of activations as there would be an output activation corresponding to each row (after multiplying with the input activation column).

Some extreme cases:

1 x 4 

![image info](1x4Weights.png)

4 x 1

![image info](4x1Weights.png)

#### BP2 matrix

While calculating BP2, we go reverse in the network, starting from the last layer. 

An example BP2 equations is :  
$\frac{\partial C}{\partial{z_1^{l-1}}} = \frac{\partial C}{\partial{z_1^{l}}}w_{11}^{l}\sigma'(z_1^{l-1}) + \frac{\partial C}{\partial{z_2^{l}}}w_{21}^{l}\sigma'(z_1^{l-1}) + \frac{\partial C}{\partial{z_3^{l}}}w_{31}^{l}\sigma'(z_1^{l-1})$  

$ = (\frac{\partial C}{\partial{z_1^{l}}}w_{11}^{l} + \frac{\partial C}{\partial{z_2^{l}}}w_{21}^{l}+\frac{\partial C}{\partial{z_3^{l}}}w_{31}^{l})\sigma'(z_1^{l-1}) $  

Similarly for second neuron in l-1 layer:

$\frac{\partial C}{\partial{z_2^{l-1}}} = (\frac{\partial C}{\partial{z_1^{l}}}w_{12}^{l} + \frac{\partial C}{\partial{z_2^{l}}}w_{22}^{l}+\frac{\partial C}{\partial{z_3^{l}}}w_{32}^{l})\sigma'(z_2^{l-1}) $ 

In summary, $ \frac{\partial C}{\partial z}$ for a neuron i in layer l-1 is sum of products of weights starting from that neuron and the error or  $\frac{\partial C}{\partial z}$ of the target neuron (and ofcourse $\sigma'(z_1^{l-1})$). 

So the initial weight matrix now needs to be transposed : rows become columns and columns become rows.

$ \begin{bmatrix} w_{11} \ w_{12} \\ w_{21} \ w_{22} \\ w_{31} \ w_{32} \end{bmatrix}$ => $ \begin{bmatrix} w_{11} \ w_{21} \ w_{31} \\ w_{12} \ w_{22} \ w_{32} \end{bmatrix}$

![transform](transform.png)  

##### BP2 representation in matrix form

$ \begin{bmatrix} \frac{\partial C}{\partial{z_1^{l-1}}} \\ \frac{\partial C}{\partial{z_2^{l-1}}} \end{bmatrix}$ = $ \begin{bmatrix} w_{11}^l \ w_{21}^l \ w_{31}^l \\ w_{12}^l \ w_{22}^l \ w_{32}^l \end{bmatrix} $ $ \begin{bmatrix} \frac{\partial C}{\partial{z_1^{l}}} \\ \frac{\partial C}{\partial{z_2^{l}}} \\ \frac{\partial C}{\partial{z_3^{l}}} \end{bmatrix}$ $ \odot \begin{bmatrix} \sigma'(z_1^{l-1}) \\ \sigma'(z_2^{l-1}) \end{bmatrix} $

#### BP4 matrix

General BP4 representation:

$ \frac{\partial C}{\partial w_{ji}^l} = \frac{\partial C}{\partial z_j^l} a_i^{l-1} $  

we need to calculate $ \frac{\partial C}{\partial w_{ji}^l} $ for all the weights for layer l, calculation of $ \frac{\partial C}{\partial w_{ji}^l} $ involves multiplication of $\frac{\partial C}{\partial z_j^l}$ for $j^{th}$ neuron in layer l and $ a_i^{l-1} $ for $i^{th}$ neuron in layer l-1. We need to do this for all pair of neurons in layer l and l-1 (j,i).  

Follows a matrix representation to get the weight matrix built from this information (Note that the activation matrix (1 x n) is a transpose of regular activation matrix of form (n x 1)):  


 $ \begin{bmatrix} \frac{\partial C}{\partial{w^l_{11}}} \ \frac{\partial C}{\partial{w^l_{12}}} \\ \frac{\partial C}{\partial{w^l_{21}}} \ \frac{\partial C}{\partial{w^l_{22}}} \\ \frac{\partial C}{\partial{w^l_{31}}} \ \frac{\partial C}{\partial{w^l_{32}}} \end{bmatrix}$ = $ \begin{bmatrix} \frac{\partial C}{\partial{z_1^{l}}} \\ \frac{\partial C}{\partial{z_2^{l}}} \\ \frac{\partial C}{\partial{z_3^{l}}} \end{bmatrix}$ $ \begin{bmatrix}  a_1^{l-1} \  a_2^{l-1} \end{bmatrix}$ =
$ \begin{bmatrix} \frac{\partial C}{\partial{z_1^{l}}}a_1^{l-1} \ \frac{\partial C}{\partial{z_1^{l}}}a_2^{l-1} \\
\frac{\partial C}{\partial{z_2^{l}}}a_1^{l-1} \ \frac{\partial C}{\partial{z_2^{l}}}a_2^{l-1} \\
\frac{\partial C}{\partial{z_3^{l}}}a_1^{l-1} \ \frac{\partial C}{\partial{z_3^{l}}}a_2^{l-1} \\
\end{bmatrix} $

In [3]:
arr1 = np.array([2,3,5]).reshape(-1,1)
arr2 = np.array([1,2,4,6]).reshape(1,-1)

print(arr1)
print(arr2)

np.dot(arr1,arr2)

[[2]
 [3]
 [5]]
[[1 2 4 6]]


array([[ 2,  4,  8, 12],
       [ 3,  6, 12, 18],
       [ 5, 10, 20, 30]])