In [1]:
import numpy as np

In [40]:
two_by_three = np.array([1,2,3,4,5,6]).reshape(2,3) # two arrays each of three elements

print("2x3\n",two_by_three)

three_by_two = np.array([1,2,3,4,5,6]).reshape(3,2) # three arrays each of two elements

print("\n3x2\n",three_by_two)


2x3
 [[1 2 3]
 [4 5 6]]

3x2
 [[1 2]
 [3 4]
 [5 6]]


#### Weights representation in NN

Consider two layers l-1 and l , where l-1 has 2 neurons while l has 3 neurons. So there would be total 2\*3 interconnections (weights) between these two layers. Each neuron in layer l is connected to two (all) neurons in layer l-1 , also there would be 2 activations (from l-1 layer neurons) being consumed by layer l neurons. And 3 activations would be output from layer l. 

z = wa + b

if w and a are represensted in matrix form, we can calculate z easily, which would also be in the matrix form.

The weights can be represented in a 3x2 matrix : (3 rows and two columns), where  
each row j represents connections into $j^{th}$ neuron of layer l from 2 neurons of layer l-1.  
each column i represents connections starting from $i^{th}$ neuron of layer l-1.

In [32]:
arr1 = np.array([2,3,5]).reshape(-1,1)
arr2 = np.array([1,2,4,6]).reshape(1,-1)

print(arr1)
print(arr2)

np.dot(arr1,arr2)

[[2]
 [3]
 [5]]
[[1 2 4 6]]


array([[ 2,  4,  8, 12],
       [ 3,  6, 12, 18],
       [ 5, 10, 20, 30]])